<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-24 at 20:39:25.
 */
class KalkTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Kalk
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Kalk;
        
        print_r($this->object);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Kalk::dodawanie
     */
    public function testDodawanie()
    {
        // Remove the following lines when you implement this test.
        return $this->assertEquals(2,$this->object->dodawanie(1, 1));
    }

}